stages:
    - test

aws_vars_exist:
    stage: test
    trigger: gitlab-org/5-minute-production-app/sandbox/test-aws-vars-exist

aws_vars_missing:
    stage: test
    trigger: gitlab-org/5-minute-production-app/sandbox/test-aws-vars-missing
