stages:
  - build
  - test

include:
  - template: 'Jobs/Build.gitlab-ci.yml'

aws_vars_missing:
  stage: test
  trigger:
    project: gitlab-org/5-minute-production-app/sandbox/test-aws-vars-missing
    branch: master

fail-db-init:
  stage: test
  trigger:
    project: gitlab-org/5-minute-production-app/sandbox/test-five-min-prod
    branch: fail-db-init
  allow_failure: true

fail-db-migrate:
  stage: test
  trigger:
    project: gitlab-org/5-minute-production-app/sandbox/test-five-min-prod
    branch: fail-db-migrate
  allow_failure: true

success:
  stage: test
  trigger:
    project: gitlab-org/5-minute-production-app/sandbox/test-five-min-prod
    branch: success
