stages:
  - build
  - test

include:
  - template: 'Jobs/Build.gitlab-ci.yml'

rptf:
  stage: test
  image: python:3
  before_script:
    - pip install rptf
  script:
    - rptf
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "gitlab-org/5-minute-production-app"'
      when: on_success 
