stages:
    - test

aws_vars_exist:
    stage: test
    trigger:
        project: gitlab-org/5-minute-production-app/sandbox/test-aws-vars-exist
        strategy: depend

aws_vars_missing:
    stage: test
    trigger:
        project: gitlab-org/5-minute-production-app/sandbox/test-aws-vars-missing
        strategy: depend

db_initialize_fail:
    stage: test
    trigger: gitlab-org/5-minute-production-app/sandbox/test-db_initialize-fail

db_initialize_success:
    stage: test
    trigger:
        project: gitlab-org/5-minute-production-app/sandbox/test-db_initialize-success
        strategy: depend

db_migrate_fail:
    stage: test
    trigger: gitlab-org/5-minute-production-app/sandbox/test-db_migrate-fail

db_migrate_success:
    stage: test
    trigger:
        project: gitlab-org/5-minute-production-app/sandbox/test-db_migrate-success
        strategy: depend

env_vars:
    stage: test
    trigger:
        project: gitlab-org/5-minute-production-app/sandbox/test-env-vars
        strategy: depend
