stages:
  - build
  - test

include:
  - template: 'Jobs/Build.gitlab-ci.yml'

rptf:
  stage: test
  image: registry.gitlab.com/sri-at-gitlab/projects/remote-pipeline-test-framework/framework/master
  script: rptf
