stages:
    - build
    - deploy

Docker Build Push:
    image: docker:stable
    services:
        - docker:stable-dind
    stage: build
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    script:
        - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
        - docker build . --tag $IMAGE_TAG
        - docker push $IMAGE_TAG

AWS Provision:
    stage: build
    script: echo "TODO Sri"

Deploy App:
    stage: deploy
    script: echo "TODO Sri"
